### ISSUE TITLE
What format is the frame timestamp in?

### ISSUE THREAD

**Issue by rk-exxec** [alliedvision/VimbaPython#23]
Hey there!
I am trying to build a FPS display. 
I am planning on using the timestamp of each frame received to calculate the actual FPS after processing.
What time unit is the Frame.get_timestamp() return value?
Or how do i get the frame time  from two timestamps?

Thanks in advance!

**Comment by NiklasKroeger-AlliedVision** [comment]
The number reported by `frame.get_timestamp()` is the elapsed time in nanoseconds (10⁻⁹ seconds) since the camera has last been power-cycled. This value is reported by the camera itself and included in the frame data received from the camera.

So if you want to get an estimate of the fps you could simply look at the difference in the reported timestamp between two consecutive frames. If you for example modify the `frame_handler` function from the [`asynchronous_grab.py`](https://github.com/alliedvision/VimbaPython/blob/master/Examples/asynchronous_grab.py) example to do the following, it will print out an estimate of the FPS based on the time elapsed between the received frames:
```python
prev_timestamp = 0  # global variable to keep track of last timestamp when new frame arrives
def frame_handler(cam: Camera, frame: Frame):
    global prev_timestamp
    this_timestamp = frame.get_timestamp()
    print(f'estimated FPS: {1/((this_timestamp - prev_timestamp)*1e-9)}')
    prev_timestamp = this_timestamp

    cam.queue_frame(frame)
```

I just ran a quick test with an Alvium 1800 U-500m and the value reported matches the one shown for received frames (Rcv) at the bottom in the Vimba Viewer:
![image](https://user-images.githubusercontent.com/61547504/97318898-a218c900-186c-11eb-9675-626b8780acae.png)

**Comment by rk-exxec** [comment]
Ah I see, thanks a lot!
