### ISSUE TITLE
python2 Support

### ISSUE THREAD

**Issue by rwreynol** [alliedvision/VimbaPython#24]
I understand this library requires Python 3.7, but a library in Python 2.7 would be greatly appreciated as I need to use python 2.7 to interact with other computers, sensors, ...

**Comment by NiklasKroeger-AlliedVision** [comment]
As you probably know Python 2.7 is [no longer supported even by the Python Software Foundation](https://www.python.org/doc/sunset-python-2/). So we will not put effort into making VimbaPython available for this version. I would *really* suggest you try to get your other systems to a newer python version.

Depending on your use case you might also be able to get away with running multiple python processes that perform different tasks and making their data available via something like [ZeroMQ](https://zeromq.org/languages/python/). This way you could implement classes in Python 2.7 to perform whatever you need them to do (record data from sensor, perform calculation, etc.) and make those functionalities available via a network connection. You could then use your Python 3.7 instance to connect to that network connection and query the data you need or perform the action you want. This would also work if both processes are running on the same machine.

You could of course also go the other way around and write a class that makes the required VimbaPython functionality available via a network connection and access that from Python 2.7. But I suggest you try to keep the majority of your new work in a supported version of Python.

I have successfully used this approach in the past where I had to use a device that was only supported on Windows machines while working on a Linux machine. I connected the device to a Windows computer, wrote a class exposing the required functionality via ZeroMQ and connected to that via the network from the Linux machine. By encapsulating the access into a class I was essentially able to use the networked device as though it was connected directly to the Linux machine.

I will close this issue since Python 2.7 support is not planned as mentioned above. However if you do have further questions regarding the ZeroMQ approach feel free to comment here again. Perhaps I can expand on some things if they are not clear from the description above.
