### ISSUE TITLE
python version 3.7 or higher

### ISSUE THREAD

**Issue by skywo1f** [alliedvision/VimbaPython#36]
I understand the first requirement is python version 3.7 or higher, but is there any way to run it with an earlier python? I am trying to run a neural network code, but it only supports python up to 3.6. Basically I am having to do something like 
python3.8 video.py | python3.6 ml.py where I am piping through images a byte at a time. This works for one image, but doing a stream of images also causes problems.

any ideas?

**Comment by NiklasKroeger-AlliedVision** [comment]
The main reason for our Python 3.7 requirement is the support for Type checking because VimbaPython is based on a C API (VimbaC) and this allows us to make sure we are handing the expected data types over to that. If you need to use a version older than Python 3.7, this type checking needs to be disabled. Some time ago we got a similar request in #16 for support of older versions and there [I explained](https://github.com/alliedvision/VimbaPython/issues/16#issuecomment-699958262) how I was able to run some rudimentary tests with Python3.6.  The general idea is to simply disable the runtime type checking by making the respective decorator a noop. To do this [comment out the functionality in the `RuntimeTypeCheckEnable.__call__` method (lines 55-58 in runtime_type_check.py)](https://github.com/alliedvision/VimbaPython/blob/916ed0561139f7c45b15e697c19c8b60ba0a19f4/vimba/util/runtime_type_check.py#L55-L58).

However please be advised, that this will mean that you are using a non-validated combination of Python and VimbaPython which may contain unexpected bugs.

I hope this helps. It has been some time since I checked this method of getting VimbaPython to run on Python versions older than 3.7, so it is possible, that further modifications may be necessary. But as far as I remember there were no changes to VimbaPython that would require further intervention.

**Comment by skywo1f** [comment]
Ill check it out, thanks

**Comment by beniroquai** [comment]
That's great! Thanks a lot for explaining it. 
Would it be possible to have that as an install flag in the pip script by any chance? This would avoid the hassle with the Jetson Nano not being able to use python3.7 and opencv (without a gigantic mess ;-)

**Comment by NiklasKroeger-AlliedVision** [comment]
Well the runtime type check does have a purpose and adding support for yet another version of Python would mean that we have a lot more work to do during validation. Especially considering that for 3.6 an important safety aspect is not working.... There are currently no concrete plans for adding official support for Python3.6.

# Python3.6 is coming to its end of life
Adding to this: Everyone using python 3.6 should probably also keep in mind, that it is coming to end of life regarding official support anyway (scheduled for 2021-12-23): https://www.python.org/downloads/. I understand that there are probably some code bases, that rely on 3.6, but I would suggest updating to newer versions of python wherever possible.

# Regarding python3.7 and opencv on the jetson nano
I believe the following steps should get you a working python3.7 venv with opencv (just writing this from memory, steps were not checked to be correct. If they do not work please let me know so I can fix these instructions.):
- install python3.7 and python3-venv (yes the python3-venv package is the one you want. There is no python3.7-venv as far as I remember) via apt
- create a new python3.7 venv in the directory where you want to store it (`python3.7 -m venv <name-of-venv>`)
- activate that venv (`source <name-of-venv>/bin/activate`)
- update pip inside that venv to at least 19.3 (with venv activated: `python -m pip install -U pip`)
- after updating pip install opencv (`pip install opencv-python`)
- run a python interpreter from that venv and try to import opencv (i.e. execute `python` on console and simply try `import cv2` in that REPL)

This is now possible thanks to OpenCV being available in a newer precompiled `manylinux` format from pip and newer versions of pip supporting this format. You can find some more information on the PyPI page for opencv-python: https://pypi.org/project/opencv-python/

**Comment by beniroquai** [comment]
Ah, interesting! Thanks a lot for the note here. I tried explaining the procedure [here](https://github.com/openUC2/UC2-Software-GIT/tree/master/GUI/NVIDIA_JETSON#1-install-python-37). It took ages!  Nice to see that it became a little easier :-)

Will try that out again.
