### ISSUE TITLE
How to detect incomplete frames properly? 

### ISSUE THREAD

**Issue by beniroquai** [alliedvision/VimbaPython#46]
When running the below code, sometimes the produced frames look like this:

![image](https://user-images.githubusercontent.com/4345528/111749768-89986200-8892-11eb-9063-734bd78473bd.png)

I'm not quite sure if this is due to the TIF framewriter or due to the camera interface. I tried catching bad frames by counting zero-pixels before and after writing to the disk. Do you have any idea what could cause this issue? The value framestate gives `complete` even if the frames are obviously not correctly written or produced. 

```py
import numpy as np
import matplotlib.pyplot as plt
import cv2
import time
import matplotlib
import sys
from typing import Optional
from vimba import *
from vimba.frame import FrameStatus
import tifffile as tif
import os

# Setup Camera
timestr = time.strftime("%Y%m%d-%H%M%S")

# Prepare Camera for ActionCommand - Trigger
myexposure = 3000/1000 # in ms 
BLACKLEVEL = 100
mygain = 0
mybasepath = "./"
myfolder = timestr + "_Texp-" + str(myexposure) + "_gain-" + str(mygain)
iiter = 0

# helper functions
def abort(reason: str, return_code: int = 1, usage: bool = False):
    print(reason + '\n')

    if usage:
        print_usage()

    sys.exit(return_code)

def get_camera(camera_id: Optional[str]) -> Camera:
    with Vimba.get_instance() as vimba:
        if camera_id:
            try:
                return vimba.get_camera_by_id(camera_id)

            except VimbaCameraError:
                abort('Failed to access Camera \'{}\'. Abort.'.format(camera_id))

        else:
            cams = vimba.get_all_cameras()
            if not cams:
                abort('No Cameras accessible. Abort.')

            return cams[0]

def setup_camera(cam: Camera):
    with cam:
        # Try to adjust GeV packet size. This Feature is only available for GigE - Cameras.
        try:
            cam.GVSPAdjustPacketSize.run()

            while not cam.GVSPAdjustPacketSize.is_done():
                pass

        except (AttributeError, VimbaFeatureError):
            pass
                
        #cam.TriggerSelector.set('FrameStart')
        #cam.TriggerActivation.set('RisingEdge')
        #cam.TriggerSource.set('Line0')
        #cam.TriggerMode.set('On')
        cam.BlackLevel.set(BLACKLEVEL)
        cam.ExposureAuto.set("Off")
        cam.ContrastEnable.set("Off")

        cam.ExposureTime.set(myexposure*1e3)
        #cam.PixelFormat.set('Mono12')
        cam.GainAuto.set("Off")
        cam.Gain.set(mygain)
        cam.AcquisitionFrameRateEnable.set(False)
        cam.get_feature_by_name("PixelFormat").set("Mono12")


try:
    os.mkdir(mybasepath+myfolder)
except:
    print("Already crated the folder?")

cam_id = 0
frameiter = 0

# Acquire Ptychograms
iiter = 0
with Vimba.get_instance():
    with get_camera(cam_id) as cam:

        setup_camera(cam)
        print('Press <enter> to stop Frame acquisition.')

        input("Plug off the laser")
        myframe = cam.get_frame().as_numpy_ndarray()
        myfilename = mybasepath+myfolder+"/Background.tif"
        tif.imsave(myfilename, myframe) #, imagej=True)
        input("Ready?")
               
        while(True):
            try:
                # take a snapshot of the secondary camera for tracking the position
                while(True):
                    myframe = cam.get_frame().as_numpy_ndarray()
                    myfilename = mybasepath+myfolder+"/"+str(iiter)+".tif" #/"+str(iiter)+"_ix_"+str(ix)+"iy_"+str(iy)+".tif"
                    frame_written = True
                    tif.imwrite(myfilename, myframe)
                    print("Frame STatus:" + str(cam.get_frame().get_status()))
                    print("Frame written:" + str(frame_written))
                    print("Frame mean:" + str(np.mean(myframe)))
                    
                    # check if data has been written to the disk correctly
                    testframe=tif.imread(myfilename)
                    N_pix_dead = np.mean(testframe<=(BLACKLEVEL-20)) # account for noise +/-
                    if  cam.get_frame().get_status() == FrameStatus.Complete and frame_written and N_pix_dead < 1000 :
                        break
                    
                    print("Detected a corrupted frame")

                iiter += 1
            except Exception as e:
                print(e)
                cam.stop_streaming()
                break
```

Is there a good practice to catch these frames? Or is it a hardware problem? 
We use a Jetson Nano with a proper USB3 cable (from AlliedVision) and the latest driver + Python version. 

Thank you!

**Comment by NiklasKroeger-AlliedVision** [comment]
This seems like you are receiving incomplete frames, so your idea of checking for the frame status is correct! Unfortunately it seems like your test is not doing what you expect.

Your example broken down. Comments for every block below the code block
```python
myframe = cam.get_frame().as_numpy_ndarray()
```
Frame is recorded by the camera and saved in `myframe`.
```python
myfilename = mybasepath+myfolder+"/"+str(iiter)+".tif" #/"+str(iiter)+"_ix_"+str(ix)+"iy_"+str(iy)+".tif"
frame_written = True
tif.imwrite(myfilename, myframe)
```
File path is assembled and `frame_written` always set to true, regardless of result of `imwrite`. So even if the image is not written successfully, `frame_written` indicates it was.
```python
print("Frame STatus:" + str(cam.get_frame().get_status()))
```
Try to print frame status. However by calling `cam.get_frame()` a new frame is recorded! This does not check the frame status of the frame that was saved to disk. Instead use `myframe.get_status()`.
```python
print("Frame written:" + str(frame_written))
```
As mentioned above, this will always print `True` even if there was a problem with writing the frame.
```python
print("Frame mean:" + str(np.mean(myframe)))
```
Print the mean brightness of the original frame. (This is not the one for which `.get_status()` was printed as that one was recorded new two lines above. See comment there.
```python
# check if data has been written to the disk correctly
testframe=tif.imread(myfilename)
```
Load the image data that was previously written (hopefully, no check if write was successful) and store it as (most likely) a numpy array in `testframe`
```python
N_pix_dead = np.mean(testframe<=(BLACKLEVEL-20)) # account for noise +/-
```
Take the mean of a mask that shows where pixel intensities lie below a theshold of `BLACKLEVEL-20`. This will essentially give a number between 0 and 1 which gives the share of pixels, that are below that threshold (0.25 -> 25% of pixels below threshold). The name (and use in next line) indicates you want to use it as a count of pixels below that intensity. For that you should sum up the mask array you are creating: `N_pix_dead = np.sum(testframe<=(BLACKLEVEL-20))`. This works because with your comparison you are creating a new numpy array, which will contain a `True` where the comparison is true and a `False` otherwise. By summing them up every `True` increments the sum by one giving you overall the count of pixels where the comparison was true.
```python
if  cam.get_frame().get_status() == FrameStatus.Complete and frame_written and N_pix_dead < 1000 :
    break

print("Detected a corrupted frame")
```
The if statement above does three things. I will break them down into separate comments again below

```python
if cam.get_frame().get_status() == FrameStatus.Complete
```
This again records a new frame. It then takes the status of that new frame and checks if the status is `FrameStatus.Complete`. Instead you should use your original frame to see if the image data in _that frame_ was complete: `myframe.get_status() == FrameStatus.Complete`.

```python
and frame_written
```
This attempts to check if the original frame was successfully written to disk. Since you always set that variable to `True` this check will always pass and essentially does nothing. You should check if the `imwrite` function used above returns some kind of success indicator you could use to set that variable.

```python
and N_pix_dead < 1000
```
As mentioned above you try to see if the count of pixels darker than a threshold is below 1000. However since you calculate a share of pixels above which will always be between 0 and 1, this comparison will also always be true. To fix this use the `np.sum()` method I described above or change the check here to see if the share of pixels is below some threshold like for example 10%. For that you should probably also change the variable name to prevent confusion later on: `share_of_dead_pixels < 0.1`

Generally the idea of checking the frame status to see if the image was complete is the correct approach. But since you record an overall of 3 frames in your checks, you are not really comparing the frame status of the original recorded frame whose image data you are using. Fully corrected I would suggest you do the following (only change the `while(True)` loop so only that is corrected below. I also removed the `frame_written` variable because I am not sure what return value `tif.imwrite` gives and if ti might be used for this check:
```python
myframe = cam.get_frame().as_numpy_ndarray()
myfilename = mybasepath+myfolder+"/"+str(iiter)+".tif" #/"+str(iiter)+"_ix_"+str(ix)+"iy_"+str(iy)+".tif"
tif.imwrite(myfilename, myframe)
print("Frame STatus:" + str(myframe.get_status()))
print("Frame written:" + str(frame_written))
print("Frame mean:" + str(np.mean(myframe)))

# check if data has been written to the disk correctly
testframe=tif.imread(myfilename)
N_pix_dead = np.sum(testframe<=(BLACKLEVEL-20)) # account for noise +/-
if  myframe.get_status() == FrameStatus.Complete and N_pix_dead < 1000 :
    break

print("Detected a corrupted frame")
```

I hope this helps. If you have further questions let me know.

**Comment by beniroquai** [comment]
Hey, wow! that was a very comprehensive answer! Thanks a lot! I feel a bit embarrassed, that I haven't seen this obvious error on my end. Changed it according to your suggestions - works. Tadah! Thanks a lot!!
