### ISSUE TITLE
build opencv 

### ISSUE THREAD

**Issue by roche-MH** [alliedvision/VimbaPython#53]
When opencv-4.5 is build, if ./install.sh is executed, opencv-python is installed. Can I use setup.py instead of install.sh?

**Comment by NiklasKroeger-AlliedVision** [comment]
Yes you can of course use `setup.py` directly. The `Install.sh` script is only meant to simplify installation for users who are not yet very familiar with the way python packages are handled. All it does is "assemble" the required arguments to perform a call to `pip` to install VimbaPython and the optional dependencies. Users who know how to do that can do so manually.

**Comment by roche-MH** [comment]
Thank you for quick response.
my version is
opencv (build): 4.5.0
Python: 3.7.4
When using Vimba (opencv support), is it just `python setup.py install`  do?

**Comment by NiklasKroeger-AlliedVision** [comment]
Yes that should do the trick.

I personally prefer to use pip to install packages, but I believe the end result should be the same with your command.

Side note: What happens if you simply select that you do not want to install opencv when running the `Install.sh` script. In that case `pip` should simply ignore that optional dependency and you may also be able to use your custom build of opencv.

**Comment by roche-MH** [comment]
yeah i try first `install.sh` and choose (opencv support No) and then run `setup.py install`
