### ISSUE TITLE
Multiprocessing Frame Queue issue

### ISSUE THREAD

**Issue by ShankssD** [alliedvision/VimbaPython#86]
Hi, 

I was initially using multithreading to acquire, (display & queue) then save the frames.  However I discovered that if the program was left for a long period of time, it would crash due to memory issues (save queue would be too large). 

As a solution I am trying to implement multiprocessing to save the frames as they are received and am using multiprocessing.queue. When trying to queue the Frame object, I run into the following error. 

`Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\multiprocessing\queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Program Files\Python39\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ctypes.c_char_Array_230400'>: attribute lookup c_char_Array_230400 on ctypes failed`

I have tried to copy.deepcopy the frame before using put(frame) but the error remains. Any help apprecieted ! 

Thanks

**Comment by NiklasKroeger-AlliedVision** [comment]
The Python `multiprocessing.queue` does a little bit more work than the `threading. queue`. The biggest difference is, that objects need to be dumped into a store- and loadable format (which is done in Python by the [pickle module](https://docs.python.org/3/library/pickle.html)). This is necessary because the processes do not share the same memory. Some more information on the intricacies of `multiprocessing.queue` can be found on [the documentation page](https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues).

You are seeing an error indicating that a `c_char_Array` cannot be pickled, because that is what VimbaPython uses for the underlying frame memory (the actual  memory where the image data is written to).

What exactly are you trying to do in the second processing you are passing your frames to? If your use case allows this it might be possible, to not pass the entire `Frame` object over to the second process, but instead take the image data and pass it as a numpy array. I believe that those should be pickleable. You can get the image data as a numpy array from your `Frame` with the [`as_numpy_ndarray()` method](https://github.com/alliedvision/VimbaPython/blob/v1.1.0/vimba/frame.py#L815-L850).
